### ISSUE TITLE
指定文件夹，自定义格式

### ISSUE THREAD

**Issue by TianBoxv587** [Hoshino-Yumetsuki/obsidian-plugin-abbrlink#1]
1. 能够指定文件夹
只有需要发布的文章才需要abbrlink
2. 能够自定义格式
比如`permalink: asdfadsfa{{abbrlink}}`

**Comment by Hoshino-Yumetsuki** [comment]
此插件为 Hexo 的 Abbelink 插件的 Obsidian 平替版，在开发时就没有考虑到其他静态生成器的链接生成，并且已经结束了快速开发周期，所以目前暂不考虑添加其他功能
